# Pandas

Pandas very useful for table data. Dataframe

In [35]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/iris.csv')

In [3]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
16            5.4          3.9           1.3          0.4     setosa
17            5.1          3.5           1.4          0.3     setosa
18            5.7          3.8           1.7          0.3     setosa
19            5.1          3.8           1.5          0.3     setosa
20            5.4          3.4           1.7          0.2     setosa
21            5.1          3.7           1.5          0.4     setosa
22            4.6          3.6           1.0          0.2     setosa
23            5.1          3.3           1.7          0.5     setosa
24            4.8          3.4           1.9          0.2     setosa
25            5.0          3.0           1.6          0.2     setosa
26            5.0          3.4           1.6          0.4     setosa
27            5.2          3.5           1.5          0.2     setosa
28            5.2          3.4           1.4          0.2     setosa
29            4.7          3.2           1.6          0.2     setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [4]:
df['petal_length'].max()

6.9

In [5]:
df['petal_length'].mean()

3.758666666666666

In [6]:
# can also create df using list of tuples
data = [
    ('ken', 24, 'red'),
    ('ben', 22, 'green'),
    ('dave', 30, 'orange')
]
pd.DataFrame(data, columns=['name', 'age', 'fav_color'])

   name  age fav_color
0   ken   24       red
1   ben   22     green
2  dave   30    orange

In [7]:
df.shape

(150, 5)

In [8]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [9]:
df.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [10]:
df[2:5]

   sepal_length  sepal_width  petal_length  petal_width species
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [11]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [12]:
list(df.columns)

['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species']

In [13]:
df.sepal_length

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
5      5.4
6      4.6
7      5.0
8      4.4
9      4.9
10     5.4
11     4.8
12     4.8
13     4.3
14     5.8
15     5.7
16     5.4
17     5.1
18     5.7
19     5.1
20     5.4
21     5.1
22     4.6
23     5.1
24     4.8
25     5.0
26     5.0
27     5.2
28     5.2
29     4.7
      ...
120    6.9
121    5.6
122    7.7
123    6.3
124    6.7
125    7.2
126    6.2
127    6.1
128    6.4
129    7.2
130    7.4
131    7.9
132    6.4
133    6.3
134    6.1
135    7.7
136    6.3
137    6.4
138    6.0
139    6.9
140    6.7
141    6.9
142    5.8
143    6.8
144    6.7
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [14]:
df['sepal_length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
5      5.4
6      4.6
7      5.0
8      4.4
9      4.9
10     5.4
11     4.8
12     4.8
13     4.3
14     5.8
15     5.7
16     5.4
17     5.1
18     5.7
19     5.1
20     5.4
21     5.1
22     4.6
23     5.1
24     4.8
25     5.0
26     5.0
27     5.2
28     5.2
29     4.7
      ...
120    6.9
121    5.6
122    7.7
123    6.3
124    6.7
125    7.2
126    6.2
127    6.1
128    6.4
129    7.2
130    7.4
131    7.9
132    6.4
133    6.3
134    6.1
135    7.7
136    6.3
137    6.4
138    6.0
139    6.9
140    6.7
141    6.9
142    5.8
143    6.8
144    6.7
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [15]:
df[['sepal_length', 'sepal_width']]

     sepal_length  sepal_width
0             5.1          3.5
1             4.9          3.0
2             4.7          3.2
3             4.6          3.1
4             5.0          3.6
5             5.4          3.9
6             4.6          3.4
7             5.0          3.4
8             4.4          2.9
9             4.9          3.1
10            5.4          3.7
11            4.8          3.4
12            4.8          3.0
13            4.3          3.0
14            5.8          4.0
15            5.7          4.4
16            5.4          3.9
17            5.1          3.5
18            5.7          3.8
19            5.1          3.8
20            5.4          3.4
21            5.1          3.7
22            4.6          3.6
23            5.1          3.3
24            4.8          3.4
25            5.0          3.0
26            5.0          3.4
27            5.2          3.5
28            5.2          3.4
29            4.7          3.2
..            ...          ...
120           6.9          3.2
121           5.6          2.8
122           7.7          2.8
123           6.3          2.7
124           6.7          3.3
125           7.2          3.2
126           6.2          2.8
127           6.1          3.0
128           6.4          2.8
129           7.2          3.0
130           7.4          2.8
131           7.9          3.8
132           6.4          2.8
133           6.3          2.8
134           6.1          2.6
135           7.7          3.0
136           6.3          3.4
137           6.4          3.1
138           6.0          3.0
139           6.9          3.1
140           6.7          3.1
141           6.9          3.1
142           5.8          2.7
143           6.8          3.2
144           6.7          3.3
145           6.7          3.0
146           6.3          2.5
147           6.5          3.0
148           6.2          3.4
149           5.9          3.0

[150 rows x 2 columns]

In [16]:
df['sepal_length']

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
5      5.4
6      4.6
7      5.0
8      4.4
9      4.9
10     5.4
11     4.8
12     4.8
13     4.3
14     5.8
15     5.7
16     5.4
17     5.1
18     5.7
19     5.1
20     5.4
21     5.1
22     4.6
23     5.1
24     4.8
25     5.0
26     5.0
27     5.2
28     5.2
29     4.7
      ...
120    6.9
121    5.6
122    7.7
123    6.3
124    6.7
125    7.2
126    6.2
127    6.1
128    6.4
129    7.2
130    7.4
131    7.9
132    6.4
133    6.3
134    6.1
135    7.7
136    6.3
137    6.4
138    6.0
139    6.9
140    6.7
141    6.9
142    5.8
143    6.8
144    6.7
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [17]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [18]:
df[df.sepal_length == df.sepal_length.max()]

     sepal_length  sepal_width  petal_length  petal_width    species
131           7.9          3.8           6.4          2.0  virginica

In [19]:
# write to csv

# df.to_csv

In [23]:
for group, group_df in df.groupby('species'):
    print(group)
    print(group_df)

setosa
    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8          4.0           1.2          0.2  setosa
15           5.7          4.4           1.5          0.4  setosa
16           5.4          3.9           1.3          0.4  setosa
17           5.1          3.5           1.4          0.3  setosa
18           5.7          3.8           1.7          0.3  setosa
19           5.1          3.8           1.5          0.3  setosa
20           5.4          3.4           1.7          0.2  setosa
21           5.1          3.7           1.5          0.4  setosa
22           4.6          3.6           1.0          0.2  setosa
23           5.1          3.3           1.7          0.5  setosa
24           4.8          3.4           1.9          0.2  setosa
25           5.0          3.0           1.6          0.2  setosa
26           5.0          3.4           1.6          0.4  setosa
27           5.2          3.5           1.5          0.2  setosa
28           5.2          3.4           1.4          0.2  setosa
29           4.7          3.2           1.6          0.2  setosa
30           4.8          3.1           1.6          0.2  setosa
31           5.4          3.4           1.5          0.4  setosa
32           5.2          4.1           1.5          0.1  setosa
33           5.5          4.2           1.4          0.2  setosa
34           4.9          3.1           1.5          0.1  setosa
35           5.0          3.2           1.2          0.2  setosa
36           5.5          3.5           1.3          0.2  setosa
37           4.9          3.1           1.5          0.1  setosa
38           4.4          3.0           1.3          0.2  setosa
39           5.1          3.4           1.5          0.2  setosa
40           5.0          3.5           1.3          0.3  setosa
41           4.5          2.3           1.3          0.3  setosa
42           4.4          3.2           1.3          0.2  setosa
43           5.0          3.5           1.6          0.6  setosa
44           5.1          3.8           1.9          0.4  setosa
45           4.8          3.0           1.4          0.3  setosa
46           5.1          3.8           1.6          0.2  setosa
47           4.6          3.2           1.4          0.2  setosa
48           5.3          3.7           1.5          0.2  setosa
49           5.0          3.3           1.4          0.2  setosa
versicolor
    sepal_length  sepal_width  petal_length  petal_width     species
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor
52           6.9          3.1           4.9          1.5  versicolor
53           5.5          2.3           4.0          1.3  versicolor
54           6.5          2.8           4.6          1.5  versicolor
55           5.7          2.8           4.5          1.3  versicolor
56           6.3          3.3           4.7          1.6  versicolor
57           4.9          2.4           3.3          1.0  versicolor
58           6.6          2.9           4.6          1.3  versicolor
59           5.2          2.7           3.9          1.4  versicolor
60           5.0          2.0           3.5          1.0  versicolor
61           5.9          3.0           4.2          1.5  versicolor
62           6.0          2.2           4.0          1.0  versicolor
63           6.1          2.9           4.7          1.4  versicolor
64           5.6          2.9           3.6          1.3  versicolor
65           6.7          3.1           4.4          1.4  versicolor
66           5.6          3.0           4.5          1.5  versicolor
67           5.8          2.7           4.1          1.0  versicolor
68           6.2          2.2           4.5          1.5  versicolor
69           5.6          2.5           3.9          1.1  versicolor
70           5.9          3.2           4.8          1.8  versicolor
71           6.1          2.8           4.0          1.3  versicolor
72           6.3          2.5           4.9          1.5  versicolor
73           6.1          2.8           4.7          1.2  versicolor
74           6.4          2.9           4.3          1.3  versicolor
75           6.6          3.0           4.4          1.4  versicolor
76           6.8          2.8           4.8          1.4  versicolor
77           6.7          3.0           5.0          1.7  versicolor
78           6.0          2.9           4.5          1.5  versicolor
79           5.7          2.6           3.5          1.0  versicolor
80           5.5          2.4           3.8          1.1  versicolor
81           5.5          2.4           3.7          1.0  versicolor
82           5.8          2.7           3.9          1.2  versicolor
83           6.0          2.7           5.1          1.6  versicolor
84           5.4          3.0           4.5          1.5  versicolor
85           6.0          3.4           4.5          1.6  versicolor
86           6.7          3.1           4.7          1.5  versicolor
87           6.3          2.3           4.4          1.3  versicolor
88           5.6          3.0           4.1          1.3  versicolor
89           5.5          2.5           4.0          1.3  versicolor
90           5.5          2.6           4.4          1.2  versicolor
91           6.1          3.0           4.6          1.4  versicolor
92           5.8          2.6           4.0          1.2  versicolor
93           5.0          2.3           3.3          1.0  versicolor
94           5.6          2.7           4.2          1.3  versicolor
95           5.7          3.0           4.2          1.2  versicolor
96           5.7          2.9           4.2          1.3  versicolor
97           6.2          2.9           4.3          1.3  versicolor
98           5.1          2.5           3.0          1.1  versicolor
99           5.7          2.8           4.1          1.3  versicolor
virginica
     sepal_length  sepal_width  petal_length  petal_width    species
100           6.3          3.3           6.0          2.5  virginica
101           5.8          2.7           5.1          1.9  virginica
102           7.1          3.0           5.9          2.1  virginica
103           6.3          2.9           5.6          1.8  virginica
104           6.5          3.0           5.8          2.2  virginica
105           7.6          3.0           6.6          2.1  virginica
106           4.9          2.5           4.5          1.7  virginica
107           7.3          2.9           6.3          1.8  virginica
108           6.7          2.5           5.8          1.8  virginica
109           7.2          3.6           6.1          2.5  virginica
110           6.5          3.2           5.1          2.0  virginica
111           6.4          2.7           5.3          1.9  virginica
112           6.8          3.0           5.5          2.1  virginica
113           5.7          2.5           5.0          2.0  virginica
114           5.8          2.8           5.1          2.4  virginica
115           6.4          3.2           5.3          2.3  virginica
116           6.5          3.0           5.5          1.8  virginica
117           7.7          3.8           6.7          2.2  virginica
118           7.7          2.6           6.9          2.3  virginica
119           6.0          2.2           5.0          1.5  virginica
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [22]:
df.groupby('species').max()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa               5.8          4.4           1.9          0.6
versicolor           7.0          3.4           5.1          1.8
virginica            7.9          3.8           6.9          2.5

In [25]:
pd.concat([df, df], ignore_index=True)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
16            5.4          3.9           1.3          0.4     setosa
17            5.1          3.5           1.4          0.3     setosa
18            5.7          3.8           1.7          0.3     setosa
19            5.1          3.8           1.5          0.3     setosa
20            5.4          3.4           1.7          0.2     setosa
21            5.1          3.7           1.5          0.4     setosa
22            4.6          3.6           1.0          0.2     setosa
23            5.1          3.3           1.7          0.5     setosa
24            4.8          3.4           1.9          0.2     setosa
25            5.0          3.0           1.6          0.2     setosa
26            5.0          3.4           1.6          0.4     setosa
27            5.2          3.5           1.5          0.2     setosa
28            5.2          3.4           1.4          0.2     setosa
29            4.7          3.2           1.6          0.2     setosa
..            ...          ...           ...          ...        ...
270           6.9          3.2           5.7          2.3  virginica
271           5.6          2.8           4.9          2.0  virginica
272           7.7          2.8           6.7          2.0  virginica
273           6.3          2.7           4.9          1.8  virginica
274           6.7          3.3           5.7          2.1  virginica
275           7.2          3.2           6.0          1.8  virginica
276           6.2          2.8           4.8          1.8  virginica
277           6.1          3.0           4.9          1.8  virginica
278           6.4          2.8           5.6          2.1  virginica
279           7.2          3.0           5.8          1.6  virginica
280           7.4          2.8           6.1          1.9  virginica
281           7.9          3.8           6.4          2.0  virginica
282           6.4          2.8           5.6          2.2  virginica
283           6.3          2.8           5.1          1.5  virginica
284           6.1          2.6           5.6          1.4  virginica
285           7.7          3.0           6.1          2.3  virginica
286           6.3          3.4           5.6          2.4  virginica
287           6.4          3.1           5.5          1.8  virginica
288           6.0          3.0           4.8          1.8  virginica
289           6.9          3.1           5.4          2.1  virginica
290           6.7          3.1           5.6          2.4  virginica
291           6.9          3.1           5.1          2.3  virginica
292           5.8          2.7           5.1          1.9  virginica
293           6.8          3.2           5.9          2.3  virginica
294           6.7          3.3           5.7          2.5  virginica
295           6.7          3.0           5.2          2.3  virginica
296           6.3          2.5           5.0          1.9  virginica
297           6.5          3.0           5.2          2.0  virginica
298           6.2          3.4           5.4          2.3  virginica
299           5.9          3.0           5.1          1.8  virginica

[300 rows x 5 columns]

In [26]:
pd.concat([df, df], ignore_index=True, axis=1)

       0    1    2    3          4    5    6    7    8          9
0    5.1  3.5  1.4  0.2     setosa  5.1  3.5  1.4  0.2     setosa
1    4.9  3.0  1.4  0.2     setosa  4.9  3.0  1.4  0.2     setosa
2    4.7  3.2  1.3  0.2     setosa  4.7  3.2  1.3  0.2     setosa
3    4.6  3.1  1.5  0.2     setosa  4.6  3.1  1.5  0.2     setosa
4    5.0  3.6  1.4  0.2     setosa  5.0  3.6  1.4  0.2     setosa
5    5.4  3.9  1.7  0.4     setosa  5.4  3.9  1.7  0.4     setosa
6    4.6  3.4  1.4  0.3     setosa  4.6  3.4  1.4  0.3     setosa
7    5.0  3.4  1.5  0.2     setosa  5.0  3.4  1.5  0.2     setosa
8    4.4  2.9  1.4  0.2     setosa  4.4  2.9  1.4  0.2     setosa
9    4.9  3.1  1.5  0.1     setosa  4.9  3.1  1.5  0.1     setosa
10   5.4  3.7  1.5  0.2     setosa  5.4  3.7  1.5  0.2     setosa
11   4.8  3.4  1.6  0.2     setosa  4.8  3.4  1.6  0.2     setosa
12   4.8  3.0  1.4  0.1     setosa  4.8  3.0  1.4  0.1     setosa
13   4.3  3.0  1.1  0.1     setosa  4.3  3.0  1.1  0.1     setosa
14   5.8  4.0  1.2  0.2     setosa  5.8  4.0  1.2  0.2     setosa
15   5.7  4.4  1.5  0.4     setosa  5.7  4.4  1.5  0.4     setosa
16   5.4  3.9  1.3  0.4     setosa  5.4  3.9  1.3  0.4     setosa
17   5.1  3.5  1.4  0.3     setosa  5.1  3.5  1.4  0.3     setosa
18   5.7  3.8  1.7  0.3     setosa  5.7  3.8  1.7  0.3     setosa
19   5.1  3.8  1.5  0.3     setosa  5.1  3.8  1.5  0.3     setosa
20   5.4  3.4  1.7  0.2     setosa  5.4  3.4  1.7  0.2     setosa
21   5.1  3.7  1.5  0.4     setosa  5.1  3.7  1.5  0.4     setosa
22   4.6  3.6  1.0  0.2     setosa  4.6  3.6  1.0  0.2     setosa
23   5.1  3.3  1.7  0.5     setosa  5.1  3.3  1.7  0.5     setosa
24   4.8  3.4  1.9  0.2     setosa  4.8  3.4  1.9  0.2     setosa
25   5.0  3.0  1.6  0.2     setosa  5.0  3.0  1.6  0.2     setosa
26   5.0  3.4  1.6  0.4     setosa  5.0  3.4  1.6  0.4     setosa
27   5.2  3.5  1.5  0.2     setosa  5.2  3.5  1.5  0.2     setosa
28   5.2  3.4  1.4  0.2     setosa  5.2  3.4  1.4  0.2     setosa
29   4.7  3.2  1.6  0.2     setosa  4.7  3.2  1.6  0.2     setosa
..   ...  ...  ...  ...        ...  ...  ...  ...  ...        ...
120  6.9  3.2  5.7  2.3  virginica  6.9  3.2  5.7  2.3  virginica
121  5.6  2.8  4.9  2.0  virginica  5.6  2.8  4.9  2.0  virginica
122  7.7  2.8  6.7  2.0  virginica  7.7  2.8  6.7  2.0  virginica
123  6.3  2.7  4.9  1.8  virginica  6.3  2.7  4.9  1.8  virginica
124  6.7  3.3  5.7  2.1  virginica  6.7  3.3  5.7  2.1  virginica
125  7.2  3.2  6.0  1.8  virginica  7.2  3.2  6.0  1.8  virginica
126  6.2  2.8  4.8  1.8  virginica  6.2  2.8  4.8  1.8  virginica
127  6.1  3.0  4.9  1.8  virginica  6.1  3.0  4.9  1.8  virginica
128  6.4  2.8  5.6  2.1  virginica  6.4  2.8  5.6  2.1  virginica
129  7.2  3.0  5.8  1.6  virginica  7.2  3.0  5.8  1.6  virginica
130  7.4  2.8  6.1  1.9  virginica  7.4  2.8  6.1  1.9  virginica
131  7.9  3.8  6.4  2.0  virginica  7.9  3.8  6.4  2.0  virginica
132  6.4  2.8  5.6  2.2  virginica  6.4  2.8  5.6  2.2  virginica
133  6.3  2.8  5.1  1.5  virginica  6.3  2.8  5.1  1.5  virginica
134  6.1  2.6  5.6  1.4  virginica  6.1  2.6  5.6  1.4  virginica
135  7.7  3.0  6.1  2.3  virginica  7.7  3.0  6.1  2.3  virginica
136  6.3  3.4  5.6  2.4  virginica  6.3  3.4  5.6  2.4  virginica
137  6.4  3.1  5.5  1.8  virginica  6.4  3.1  5.5  1.8  virginica
138  6.0  3.0  4.8  1.8  virginica  6.0  3.0  4.8  1.8  virginica
139  6.9  3.1  5.4  2.1  virginica  6.9  3.1  5.4  2.1  virginica
140  6.7  3.1  5.6  2.4  virginica  6.7  3.1  5.6  2.4  virginica
141  6.9  3.1  5.1  2.3  virginica  6.9  3.1  5.1  2.3  virginica
142  5.8  2.7  5.1  1.9  virginica  5.8  2.7  5.1  1.9  virginica
143  6.8  3.2  5.9  2.3  virginica  6.8  3.2  5.9  2.3  virginica
144  6.7  3.3  5.7  2.5  virginica  6.7  3.3  5.7  2.5  virginica
145  6.7  3.0  5.2  2.3  virginica  6.7  3.0  5.2  2.3  virginica
146  6.3  2.5  5.0  1.9  virginica  6.3  2.5  5.0  1.9  virginica
147  6.5  3.0  5.2  2.0  virginica  6.5  3.0  5.2  2.0  virginica
148  6.2  3.4  5.4  2.3  virginica  6.2  3.4  5.4  2.3  virginica
149  5.9  3.0  5.1  1.8  virginica  5.9  3.0  5.1  1.8  virginica

[150 rows x 10 columns]

In [28]:
temperature_df = pd.DataFrame({
    'city': ['Trivandrum', 'Ernakulam', 'Thrissur'],
    'temperature': [30, 35, 38]
})

In [29]:
humidity_df = pd.DataFrame({
    'city': ['Trivandrum', 'Ernakulam'],
    'humidity': [80, 90]
})

In [33]:
pd.merge(temperature_df, humidity_df, on='city', how='outer')

         city  temperature  humidity
0  Trivandrum           30      80.0
1   Ernakulam           35      90.0
2    Thrissur           38       NaN

In [40]:
df = pd.DataFrame(list(range(10)), index=list(np.arange(10) * 2))
df

    0
0   0
2   1
4   2
6   3
8   4
10  5
12  6
14  7
16  8
18  9

In [48]:
df.loc[0]

0    0
Name: 0, dtype: int64

In [47]:
df.loc[2]

0    1
Name: 2, dtype: int64

In [49]:
df.loc[4]

0    2
Name: 4, dtype: int64

In [44]:
df.iloc[6]

0    6
Name: 12, dtype: int64

In [50]:
df.loc[:10]

    0
0   0
2   1
4   2
6   3
8   4
10  5

In [51]:
# iloc can be thought of as integer location, or as the i in a traditional for loop setup
# loc is a lookup based on whatever the value is in the index